[package]
name = "igri"
version = "0.1.1"
edition = "2018"
description = "ImGUI runtime inspector"
license = "MIT"

[features]
dummy = ["igri_derive/dummy"]

[dependencies]
imgui = "0.8.0"
igri_derive = { path = "../igri_derive", version = "0.1.1" }
paste = "1.0.5"

